class CreateAccessRight < ActiveRecord::Migration
  def change
    create_table :access_rights do |t|
      t.boolean :user_id
      t.boolean :constructionmanageradministration
      t.boolean :databackup
      t.boolean :customers_add
      t.boolean :customers_edit
      t.boolean :customers_delete
      t.boolean :customers_applications_add
      t.boolean :customers_applications_edit
      t.boolean :customers_applications_delete
      t.boolean :customers_applications_certify_post
      t.boolean :customers_applications_salesinvoices
      t.boolean :customers_certificates_post
      t.boolean :customers_certificates_delete
      t.boolean :customers_receipts_new
      t.boolean :customers_receipts_delete
      t.boolean :customers_invoices_newinvoice
      t.boolean :customers_invoices_newcredit
      t.boolean :customers_invoices_edit
      t.boolean :customers_invoices_delete
      t.boolean :customers_invoices_invoicing
      t.boolean :customers_invoices_post
      t.boolean :suppliers_new
      t.boolean :suppliers_edit
      t.boolean :suppliers_delete
      t.boolean :suppliers_invoice_newinvoice
      t.boolean :suppliers_invoice_newcredit
      t.boolean :suppliers_invoice_edit
      t.boolean :suppliers_invoice_delete
      t.boolean :suppliers_invoice_post
      t.boolean :suppliers_products_in
      t.boolean :suppliers_products_out
      t.boolean :suppliers_products_edit
      t.boolean :suppliers_products_delete
      t.boolean :suppliers_purchaseorders_new
      t.boolean :suppliers_purchaseorders_edit
      t.boolean :suppliers_purchaseorders_delete
      t.boolean :suppliers_purchaseorders_order
      t.boolean :suppliers_purchaseorders_goodsreceived
      t.boolean :suppliers_purchaseorders_update
      t.boolean :suppliers_purchaseorders_orderactivity
      t.boolean :suppliers_purchaseorders_post
      t.boolean :suppliers_purchaseorders_approval
      t.boolean :subcontractors_applications_new
      t.boolean :subcontractors_applications_edit
      t.boolean :subcontractors_applications_delete
      t.boolean :subcontractors_applications_certify_post
      t.boolean :subcontractors_certificates_new
      t.boolean :subcontractors_certificates_batch
      t.boolean :subcontractors_certificates_edit
      t.boolean :subcontractors_certificates_delete
      t.boolean :subcontractors_certificates_post
      t.boolean :subcontractors_worksheets_new
      t.boolean :subcontractors_worksheets_edit
      t.boolean :subcontractors_worksheets_certify_post
      t.boolean :subcontractors_worksheets_delete
      t.boolean :subcontractors_payments_new
      t.boolean :subcontractors_payments_edit
      t.boolean :subcontractors_payments_delete
      t.boolean :subcontractors_payments_post
      t.boolean :subcontractors_returns_new
      t.boolean :subcontractors_returns_edit
      t.boolean :subcontractors_returns_delete
      t.boolean :subcontractors_returns_esubmissions
      t.boolean :subcontractors_pop_new
      t.boolean :subcontractors_pop_edit
      t.boolean :subcontractors_pop_delete
      t.boolean :subcontractors_pop_application
      t.boolean :subcontractors_pop_certify
      t.boolean :subcontractors_pop_approval_post
      t.boolean :contracts_new
      t.boolean :contracts_edit
      t.boolean :contracts_delete
      t.boolean :contracts_editnotes
      t.boolean :contracts_changestatus
      t.boolean :contracts_jobmanagement_activity
      t.boolean :contracts_jobmanagement_wip
      t.boolean :contracts_jobmanagement_adjustments
      t.boolean :contracts_jobmanagement_valuation
      t.boolean :labour_labourratesvisible
      t.boolean :labour_delete
      t.boolean :labour_edit
      t.boolean :labour_timesheets_new
      t.boolean :labour_timesheets_edit
      t.boolean :labour_timesheets_delete
      t.boolean :labour_timesheets_post
      t.boolean :labour_employees_new
      t.boolean :labour_employees_edit
      t.boolean :labour_employees_delete
      t.boolean :labour_payrates_new
      t.boolean :labour_payrates_edit
      t.boolean :labour_payrates_delete
      t.boolean :labour_paygroups
      t.boolean :maintenance_add
      t.boolean :maintenance_edit
      t.boolean :maintenance_delete
      t.boolean :maintenance_jobprogress
      t.boolean :maintenance_invoice
      t.boolean :maintenance_repetitions
      t.boolean :maintenance_scheduleofrates
      t.boolean :calendar_add
      t.boolean :calendar_edit
      t.boolean :calendar_delete
      t.boolean :plant_add
      t.boolean :plant_edit
      t.boolean :plant_delete
      t.boolean :plant_pop
    end
  end
end
